### ISSUE TITLE
README: Installation has incorrect instructions.

### ISSUE THREAD

**Issue by theshatterstone** [Jobin-Nelson/org-tangle.nvim#1]
Hi, Thank you for this plugin.

The README seems to contain incorrect install instructions referring to telescope-projects instead of org-tangle. Would you consider updating that? Cheers,

**Comment by Jobin-Nelson** [comment]
This plugin is no longer maintained, since https://github.com/nvim-orgmode/orgmode, has tangle feature inbuilt now

**Comment by theshatterstone** [comment]
Yeah, I discovered that later and forgot to close the issue, sorry about that!
